- blatann/examples/glucose_peripheral.py
- blatann/examples/peripheral.py
- blatann/examples/peripheral_device_info_service.py
- blatann/services/ble_data_types.py
- blatann/services/glucose/__init__.py
- blatann/services/glucose/data_types.py
- blatann/services/glucose/database.py
- blatann/services/glucose/racp.py
- blatann/services/glucose/service.py
- Implements the Glucose Server
- Adds example of glucose server
> Glucose Server

- blatann/event_args.py
- blatann/examples/central.py
- blatann/examples/central_battery_service.py
- blatann/examples/central_device_info_service.py
- blatann/examples/peripheral_battery_service.py
- blatann/services/battery/__init__.py
- blatann/services/battery/constants.py
- blatann/services/battery/data_types.py
- blatann/services/battery/service.py
- blatann/services/device_info/service.py
Implements Central and Peripheral handlers (and examples) for the Bluetooth SIG Battery service
> Battery Service

- .idea/inspectionProfiles/Project_Default.xml
- README.md
- blatann/event_args.py
- blatann/examples/glucose_peripheral.py
- blatann/examples/peripheral.py
- blatann/gap/smp.py
- blatann/nrf/nrf_driver.py
- blatann/nrf/nrf_events/__init__.py
- blatann/nrf/nrf_events/smp_events.py
- blatann/nrf/nrf_types/smp.py
Adds in support for LE Secure connection pairing modes. Tested on the peripheral side using Numeric Comparison. Central workflow not tested, but the workflow is identical
> LE Secure Connections pairing

- .idea/blatann.iml
- blatann/examples/glucose_peripheral.py
- blatann/gap/smp.py
- blatann/gap/smp_crypto.py
- setup.py
Also moves all crypto-related functions into its own source file
> removes pycrypto (dead) lib as a dependency and only uses cryptography

- README.md
- blatann/device.py
- blatann/event_args.py
- blatann/examples/centeral_uart_service.py
- blatann/examples/peripheral_uart_service.py
- blatann/gap/__init__.py
- blatann/gatt/__init__.py
- blatann/nrf/nrf_driver.py
- blatann/nrf/nrf_events/__init__.py
- blatann/nrf/nrf_events/gatt_events.py
- blatann/nrf/nrf_events/generic_events.py
- blatann/nrf/nrf_types/generic.py
- blatann/peer.py
- blatann/services/nordic_uart/__init__.py
- blatann/services/nordic_uart/constants.py
- blatann/services/nordic_uart/service.py
- Adds support for configuring MTU size per-connection
- Adds support for Data Length Extensions BLE feature
- Adds in the Nordic UART Service (Client + Peripheral)
> Configurable MTU

- blatann/device.py
- blatann/nrf/nrf_driver.py
Adds feature to allow the device's MAC address to be modified. Also updates the nRF driver level to allow variables to be returned while error codes are checked
> Change MAC Address

- .idea/blatann.iml
- Makefile
- README.md
- blatann/device.py
- blatann/event_type.py
- blatann/utils/__init__.py
- blatann/uuid.py
- requirements.txt
- setup.py
- tests/integrated/.gitignore
- tests/integrated/base.py
- tests/integrated/test_advertising.py
- Adds Makefile for package generation and test running
- Moves project requirements into a `requirements.txt` file
- Adds a couple utility functions mostly useful for testing (event subscription context, Stopwatch class, random UUID generators)
- Adds base TestCase class which configures the nordic devices
- Adds test utility decorators for defining test parameters and long-running tests
- Start of advertising tests (need second nordic device to operate as scanner for rest of tests)
> setting up infrastructure for integrated tests

- blatann/examples/centeral_uart_service.py
- blatann/examples/peripheral_uart_service.py
- blatann/gap/advertising.py
- blatann/gap/scanning.py
- blatann/gatt/service_discovery.py
- blatann/nrf/nrf_types/gap.py
- blatann/peer.py
- blatann/waitables/connection_waitable.py
- blatann/waitables/event_waitable.py
- blatann/waitables/waitable.py
- adds param validation to advertising, scan, and connection time parameters
- adds some missing type annotations for the `Peer` class(es)
- adds property to peer which exposes the currently configured connection parameters
- fixes a few potential issues around the disconnection waitable and waitables in general
- updates the nordic UART examples to use a more aggressive connection interval
- exposes the database discovery event in the `Peripheral` class
> Minor Enhancements

- README.md
- blatann/device.py
- blatann/gap/advertise_data.py
- blatann/waitables/event_waitable.py
- blatann/waitables/waitable.py
- docs/source/architecture.rst
- docs/source/changelog.rst
- docs/source/conf.py
- docs/source/examples.rst
- docs/source/getting_started.rst
- docs/source/index.rst
- docs/source/troubleshooting.rst
- Add link to readthedocs in readme, other minor updates to readme
- Adds changelog page
- Adds more content to architecture
- Adds more content to various classes/methods, param/return types documented, etc.
> adds more content to the docs

- README.md
- blatann/bt_sig/assigned_numbers.py
- blatann/device.py
- blatann/event_type.py
- blatann/gap/advertise_data.py
- blatann/gap/advertising.py
- blatann/gap/scanning.py
- blatann/gap/smp.py
- blatann/gatt/__init__.py
- blatann/gatt/gattc.py
- blatann/gatt/gattc_attribute.py
- blatann/gatt/gatts.py
- blatann/gatt/gatts_attribute.py
- blatann/gatt/service_discovery.py
- blatann/peer.py
- blatann/uuid.py
- blatann/waitables/event_waitable.py
- blatann/waitables/scan_waitable.py
- docs/source/architecture.rst
- docs/source/blatann.rst
- docs/source/conf.py
- docs/source/core_classes.rst
- docs/source/index.rst
> Documentation cleanup and improvements

- blatann/device.py
- blatann/event_args.py
- blatann/event_type.py
- blatann/nrf/nrf_driver.py
- blatann/nrf/nrf_types/config.py
- blatann/peer.py
- blatann/waitables/event_waitable.py
- tests/integrated/test_gatt_writes.py
Adds support for changing the PHY of a connection. Currently only 1Mbps and 2Mbps PHYs are supported, not Coded.
Also adds support for modifying Softdevice options using` ble_opt_set`
> PHY updates

- blatann/gatt/gattc.py
- tests/integrated/helpers.py
- tests/integrated/test_gatt.py
- tests/integrated/test_gatt_writes.py
- Adds GATT tests for happy-path read, write, and discovery. More tests to come...
- Refactors some common/shared test logic into its own file
- Adds two new characteristic properties for determining if a characteristic is configured for notifications vs indications
> adds read/write/discovery happy-path integration tests

- blatann/gatt/__init__.py
- blatann/gatt/gattc.py
- blatann/gatt/service_discovery.py
- blatann/nrf/nrf_types/gatt.py
- blatann/uuid.py
Updates descriptor discovery so unnecessary handles are skipped. Service handle and characteristic declaration/value handles will no longer be targeted for descriptor discovery
Also reduces the likelihood of running into #66
> updates characteristic descriptor discovery to be more efficient

- blatann/nrf/nrf_driver.py
Reduces contention when using multiple Nordic devices/instances
> moves driver API lock to instance-level instead of class level

- blatann/gatt/managers.py
- tests/integrated/test_gatt.py
> Fixes issue with indication waitables not notifying correctly

- .idea/blatann.iml
- README.md
- blatann/device.py
- blatann/examples/broadcaster.py
- blatann/gap/advertising.py
- blatann/nrf/nrf_driver.py
- blatann/nrf/nrf_types/gap.py
> Adds APIs for setting tx power and advertising channel masks

- blatann/examples/peripheral_rssi.py
- blatann/nrf/nrf_driver.py
- blatann/nrf/nrf_events/__init__.py
- blatann/nrf/nrf_events/gap_events.py
- blatann/peer.py
- tests/integrated/test_gap.py
> #97: Adds support to get RSSI of an active connection

- blatann/bt_sig/uuids.py
- blatann/device.py
- blatann/gatt/__init__.py
- blatann/gatt/gattc.py
- blatann/peer.py
- docs/Makefile
- docs/requirements.txt
- docs/source/blatann.examples.peripheral_rssi.rst
- docs/source/blatann.examples.rst
- docs/source/blatann.gap.gap_types.rst
- docs/source/blatann.gap.rst
- Flag some internal methods as `:meta private:` so they arent exported
- Updates docs build reqs
- Updates BT Sig defined UUIDs to latest
> Docs update

- blatann/device.py
- blatann/nrf/nrf_driver.py
- blatann/nrf/nrf_types/gap.py
- tests/integrated/test_gap.py
Adds the ability to set privacy parameters for advertising/connections
Fixes #127
> Adds support to enable private resolvable/nonresolvable addresses

- blatann/nrf/nrf_types/config.py
- tests/integrated/test_gatt.py
> Fixes issue where service changed characteristic wasn't getting added

- blatann/device.py
> Adds parameter to BleDevice.configure() to configure the event length

- blatann/device.py
- blatann/peer.py
- tests/integrated/helpers.py
- tests/integrated/test_gap.py
> #143: Add parameters to set the preferred MTU and PHY for central connections

- blatann/services/glucose/database.py
- blatann/services/glucose/service.py
> #145: Glucose service first/last record fix

- docs/source/troubleshooting.rst
> Adds section to troubleshooting for no_mem errors when increasing # connections

- setup.py
> #153: removes wildcard patch version from python_requires

- README.md
Also some other cleanup in the readme
> Removes references to python 2.7 in readme

- docs/source/troubleshooting.rst
Improvements to Troubleshooting in docs; added intro and improved (sub)section titles, re-ordered and hopefully improved readability of several text portions. Added specifics for using nRF52840-Dongle in Linux.
> Improvements to Troubleshooting in docs

- Makefile
- pyproject.toml
Adds initial configuration for ruff/isort to project. Also clean up makefile a bit.
Lint/isort cleanup later
> Add ruff/isort tooling

- docs/requirements.txt
- docs/source/blatann.examples.central_async.rst
- docs/source/blatann.examples.central_uart_service.rst
- docs/source/blatann.examples.peripheral_async.rst
- docs/source/blatann.examples.rst
- docs/source/blatann.examples.scanner_async.rst
- docs/source/blatann.gap.rst
- docs/source/blatann.gap.smp_types.rst
- docs/source/blatann.waitables.event_queue.rst
- docs/source/blatann.waitables.rst
- docs/source/conf.py
- docs/source/core_classes.rst
Updates apidoc files and adjust sphinx package versions so all plugins align
> Docs update prep for v0.6.0
