blatann/event_args.py, blatann/gatt/gattc.py, blatann/gatt/gatts.py, blatann/gatt/reader.py, blatann/gatt/writer.py, blatann/services/glucose/service.py, blatann/utils/queued_tasks_manager.py, blatann/waitables/event_waitable.py
Adds queue to facilitate reads/writes with a client connection, since only one GATTC operation can be active at a time
=> Client read write queue

blatann/services/current_time/service.py
Explicit check of total_seconds < 1 was preventing dates in the
past from being set
=> Fix handling of timedelta in current time service

blatann/nrf/nrf_driver.py
The event handlers dictionary was getting shallow-copied when processing an event, such that the handler list attached to each key could be modified when iterating over the handler list. This causes issues when a handler unregisters itself when processing the event, thus modifying the list as it's being iterated and causing the next handler to be skipped.
This changes it such that the handler list for each dict entry is copied as well
=> Fixes bug where driver event handlers may not be called if unsub happened during event handling

blatann/event_type.py, blatann/gap/advertise_data.py, blatann/gap/advertising.py, blatann/gap/scanning.py, blatann/nrf/nrf_driver.py, blatann/nrf/nrf_types/gap.py, blatann/utils/__init__.py, tests/integrated/.gitignore, tests/integrated/base.py, tests/integrated/test_advertising.py, tests/integrated/test_advertising_data.py, tests/integrated/test_advertising_duration.py
- Adds tests around advertising data, integrates a second scanner device to verify over-air data and durations
- Adds a couple features around advertising/scanning
- Active scanning is now configurable
- Can now get the raw advertising payload in `bytes`
- Adds a context manager returned from `event.register()` so it can be used as `with some_event.register(handler):`
- Adds the serial port name to the driver function call log messages (for multi-device setups)
- Fixes some issues around restarting advertising
- Cleans up the AdvertisingData class a bit (api should be backwards compatible)
=> Advertising data testing

README.md, tests/integrated/base.py, tests/integrated/test_advertising_data.py, tests/integrated/test_advertising_duration.py, tests/integrated/test_scanner.py
- nRF52840 USB dongles need a bit of time to reset after closing before reopening in between test classes
- Adds helper `assertDeltaWithin` method to `BlatannTestCase` base class
- Fixes some incorrect log messages when running parameterized tests
- Allows specific test parameters to be marked `long_running` to be skipped when `BLATANN_QUICK_TESTS=1` so some test parameters can still run for a test case
- long-running parameters are still marked as `skipped`
- Adds Scanner test cases
- Moves `test_non_active_scanning_no_scan_response_packets_received` under `TestScanner` class since it's testing scanning functionality
=> adds tests for scanning, minor updates to test infrastructure

docs/requirements.txt
Need deps to be installed for the autodoc to work on readthedocs. For some reason the `pc-ble-driver-py>=0.13` version specifier in the normal requirements.txt isn't working so adding it here without version specifier to be installed
=> add pc-ble-driver-py to docs/requirements.txt

blatann/gatt/gatts.py
It was not possible to add a characteristic with `write without response` properties, because it was hard coded to `False`.
Fixed it, so the given `properties.write_no_response` value is now respected 😉
=> Fix: Characteristics with `write without response` property

blatann/device.py, blatann/event_args.py, blatann/gatt/gattc.py, blatann/gatt/gatts.py, blatann/gatt/writer.py, blatann/nrf/nrf_driver.py, blatann/nrf/nrf_events/__init__.py, blatann/nrf/nrf_events/gatt_events.py, blatann/nrf/nrf_events/generic_events.py, blatann/nrf/nrf_types/gatt.py, blatann/peer.py, blatann/utils/__init__.py, tests/integrated/test_gatt_writes.py
Includes a test suite which demos the throughput of using write with responses vs without, using 247 MTU/251 Data Length. In general the throughput doubles without responses (15 kB/s vs 7.5 kB/s, using nRF52840 USB dongles)
Other changes:
- Updates the default connection event length to support the max data length (251)
- Adds method to trigger data length update procedure on a connection
- Adds utility class `SynchronousMonotonicCounter` to remove some duplicate logic
Fixes #37
=> adds support for performing write without responses as a GATT Client

blatann/gap/advertising.py
Also adds property for `auto_restart` so it can be set independently
Fixes #42
=> Keep is_advertising flag set true during timeout if auto-restart is enabled

blatann/examples/central.py, blatann/gap/scanning.py, blatann/gap/smp.py, blatann/nrf/nrf_driver.py, blatann/nrf/nrf_events/__init__.py, blatann/nrf/nrf_events/smp_events.py, blatann/nrf/nrf_types/enums.py
- Fixes issue initiating encryption with an already-bonded device as a central
- Adds support for handling peer-initiated security. Currently automatically handled
- Adds BLE error codes to the `NrfError` enum
=> Security fixes

blatann/device.py, blatann/event_args.py, blatann/event_type.py, blatann/examples/central.py, blatann/gap/__init__.py, blatann/gap/advertise_data.py, blatann/gap/bond_db.py, blatann/gap/default_bond_db.py, blatann/gap/smp.py, blatann/nrf/nrf_types/smp.py, blatann/peer.py, tests/integrated/base.py, tests/integrated/test_security.py
Adds numerous improvements to how bonding/pairing is handled for connections
- Adds several events and properties to get details on current connection, update security params, etc.
- Expands the `reject_pairing_requests` field to be a bitfield enum so certain pairing requests can be rejected but others accepted
- `True`/`False` still accepted and maps to the enum values `reject_all_requests` and `allow_all`, respectively
- adds handling for peripheral-initiated security/pairing requests
- Adds `name` property for peers that is populated from scan reports (for peripheral peers). Can also be set manually. Is used for bonding data as well
- Adds some integration tests around security, much more is needed still
- Adds device-level method to set the default security parameters for all …
=> Security Manager improvements

blatann/bt_sig/assigned_numbers.py, blatann/device.py, blatann/examples/peripheral.py, blatann/gap/advertise_data.py, blatann/gap/generic_access_service.py, blatann/nrf/nrf_driver.py, blatann/nrf/nrf_types/config.py, blatann/nrf/nrf_types/gap.py, docs/source/blatann.examples.multirole.rst, docs/source/blatann.examples.rst, docs/source/blatann.gap.generic_access_service.rst, docs/source/blatann.gap.rst
Can set/get:
- Device Name
- Appearance (enum added)
- Preferred Peripheral Connection Parameters
Other Advertising Data Improvements:
- Can now use `bytes` for advertising data types (e.g. `AdvertisingData(service_data=b"abcd")`)
- Can use any object type in advertising data if it has an `as_bytes()` method that can be used to convert the object to bytes
=> adds support for setting parameters in the Generic Access Service

blatann/device.py, blatann/gatt/__init__.py, blatann/gatt/gattc.py, blatann/gatt/gattc_attribute.py, blatann/gatt/gatts.py, blatann/gatt/managers.py, blatann/gatt/writer.py, blatann/nrf/nrf_types/gap.py, blatann/peer.py, blatann/services/glucose/service.py, blatann/utils/queued_tasks_manager.py, tests/integrated/test_gatt_writes.py
Changes take advantage of the Notification and Write command queues present on the Nordic S132 softdevice in order to increase throughput.
- Both Notification and Write Command queues default to 16, configurable when creating the BLE Device (slight departure from the `configure()` method, but is needed to initialize the software-mirrored queue when the device is created)
- Software queueing is still used for instances where > 16 notifications/write commands are queued up at once. New approach is more or less a 2-stage queue-- first input stage is unlimited and the second is hardware-limited
- Notifications and Write commands are handled by separate `QueuedTaskManager`s from their Indication and read/write request counterparts to facilitate this behavior. Indications, Read requests and …
=> Adds support for using the SoftDevice Tx queues for notifications and write commands

blatann/gap/smp.py
I am using two Nordic Dongles with blatann, one as Central, the other as Peripheral. Pairing and Bonding works, but when I try to re-connect the bonded devices, I get a mic failure. I think pair() should use the peers ltk when it is called on the Central device, at least it works with my two dongles (I was able to re-connect from a smartphone to the Peripheral-Dongle, so I expected the Central dongle to cause the issue)
=> - use the peers ltk for ble_gap_encrypt (peer is peripheral)

blatann/gatt/gatts.py
This might be related to https://github.com/ThomasGerstenberg/blatann/issues/10:
It would be good to set the security level for writing a cccd. 
Example: 
You have a service for bi-directional communication. The service has a notification characteristic for receiving data and a write-no-response (for maximum throughput) for sending data. The communication should be encrypted.
Currently there is no trigger to enforce encryption even if both characteristics have a security level > SecurityLevel.OPEN 
Being able to assign e.g. SecurityLevel.JUST_WORKS for writing to the cccd of the notification would trigger a "Insufficient Authentication" response which then results in a pairing/bonding
=> - add a security level for writing the cccd (reading is always allowed)

blatann/event_args.py, blatann/gap/smp.py, blatann/nrf/nrf_types/smp.py, tests/integrated/test_security.py
Fixes several issues with bonding and improves test coverage
- LESC bond restoration requires using our own LTKs. This is different than legacy encryption which uses the peer's LTKs
- Improves how bond data records are found in the bond database. For LESC bonds it was incorrectly trying to match against Master IDs which are only used for legacy pairing
- Adds new field to `PairingCompleteEventArgs` indicating the security process that completed (encryption, pairing, or bonding)
- Increases test coverage for bonding scenarios, including legacy bonding. Previous version of tests were only creating LTKs but did not attempt to reconnect and re-establish encryption using said LTKs
=> Bonding improvements

blatann/device.py, blatann/gap/default_bond_db.py, tests/integrated/base.py
Also moves the bond db file to be saved to `~/.blatann` by default. For the previous implementation `"system"` can be specified to save it within package contents
Fixes #60
=> adds bond db file param to the BleDevice constructor

blatann/gap/default_bond_db.py
```EOFError' object has no attribute 'message'```
was raised inside the `except Exception as e` block. 
The `message` attribute is not available in Python >= 3.
=> Fixed uncaught exception that could occur inside a failed to load bond db exception.

README.md, docs/source/getting_started.rst, tools/macos_retarget_pc_ble_driver_py.sh
Replaces example in readme/docs with version that's fleshed out and should run as-is in most environments
=> add macos shell script to retarget pc-ble-driver-py

blatann/services/glucose/database.py
In Python 2, `filter(...)` returns a list. https://docs.python.org/2/library/functions.html#filter
In Python 3, `filter(...)` returns an Iterable. https://docs.python.org/3/library/functions.html#filter
This pull request updates `BasicGlucoseDatabase._get_records_in_range(...)` so that it returns a list instead of an Iterable.
=> Fix BasicGlucoseDatabase for Python 3

blatann/nrf/nrf_driver.py
Hopefully this fixes issue #93
=> Use intermediate local variables when creating swig arrays instead of direct cast()

blatann/device.py, blatann/event_args.py, blatann/examples/peripheral.py, blatann/gap/__init__.py, blatann/gap/bond_db.py, blatann/gap/gap_types.py, blatann/nrf/nrf_types/gap.py, blatann/peer.py, blatann/waitables/waitable.py, tests/integrated/helpers.py, tests/integrated/test_gap.py
Addresses #102
- Adds event that triggers when connection parameters are updated
- Adds ability to configure how a central device handles peripheral-initiated connection parameter update requests
- Accept all, reject all, or set custom handler
- Default functionality is to accept all peripheral requests
- Integrated tests for connection parameter update sequences
Other changes:
- Moved some class definitions from `peer.py` into new `gap_types.py`, required to address circular dependency. Shouldn't be breaking due to the classes still being imported in `peer.py`
- Removed the "exception in exception" when a timeout is triggered from `EventWaitable.wait()`
=> Connection Parameter Update Event

blatann/gap/advertise_data.py
When UUID16 or UUID128 advertising data is decoded it was assumed the
packet was correctly formatted and of the correct multiple bytes.
Instead, incorrect multiples will have trailing bytes stripped off and
ignored (with log message).
Fixes #104
=> Fixes IndexError in AdvertisingData

blatann/gap/advertise_data.py, blatann/nrf/nrf_types/gap.py
This feature isn't supported until SoftDevice v6, but #105 reports seeing value 127 (defined [here](https://github.com/NordicSemiconductor/pc-ble-driver/blob/master/include/sd_api_v6/ble_gap.h#L209) in v6)
=> Support anonymous advertising packets

blatann/gatt/managers.py
Fix one `GattOperationCompleteReason.TIMEOUT` left in the code
=> Fix Timed_out spelling

.idea/blatann.iml, blatann/device.py, blatann/gap/bond_db.py, blatann/gap/default_bond_db.py, blatann/gap/smp.py, blatann/nrf/nrf_types/smp.py, tests/integrated/.gitignore, tests/integrated/base.py, tests/integrated/test_security.py
- Adds logic to save/load bond databases in JSON format
- Both pickle and JSON formats are supported, however JSON is the preferred method going forward
- Adds migration logic to convert existing pickle bond dbs to json
- the `"user"` and `"system"` special filenames are migrated automatically. Other specified filenames need to be manually migrated using `blatann.default_bond_db.migrate_bond_database(from_file, to_file)`
- Bonding records are now aware of the nRF's device address. In the case that multiple nRF devices are used, it will not match a bond entry for a different dev board/dongle
- Logic for matching a bond entry to a peer's info is moved from the SecurityManager into the BondDbEntry (precursor to #130)
=> Replaces the default Bond DB format from pkl to json

README.md, blatann/gap/advertise_data.py, blatann/gap/bond_db.py, blatann/gap/scanning.py, tests/integrated/test_security.py
- Scanner will now check the bond database when it receives a packet if the address resolves to a bonded device
- ScanReport will use the resolved address as a key for the `_scans_by_peer_address` dict
Fixes #130
=> #130: Adds support for scanner to resolve peer addresses

blatann/device.py, blatann/gap/default_bond_db.py, tests/integrated/base.py
Adds special bond db filename `:memory:` to signify the bond database should not be written to disk
Fixes #142
=> #142: adds in-memory bond database strategy

blatann/gatt/gatts.py
fixes issue where the string encoding was being set as the gatt characteristic attributes
Also renames private `_attrs` var to match overridden value
=> characteristic attributes fix

README.md
Added/updated links to compatible nRF52 hardware.
The link for the ABSniffer 528 blog post wasn't working anymore, so this has been updated to a different resource.
For the Nordic Semiconductor products the original text was clear on the nRF52840-Dongle, but just mentioning _"both the nRF52 Dev Kits"_ wasn't... As the _"Development kits for the nRF52 Series"_ section of the [Nordic Semiconductor BLE Hardware](https://www.nordicsemi.com/Products/Bluetooth-Low-Energy/Development-hardware) page lists three (3) Dev Kits for the nRF52 series. So **_"both"_** wasn't explicit enough.
The table showed that "both Dev Kits" actually refers to the nRF52833-DK and the nRF52840-DK, so this has been made more explicit in this PR with the hardware enumeration providing the names and links.
=> Added/updated links to compatible nRF52 hardware

docs/source/compatibility_matrix.rst
The "Python Version Version" header had a double Version; while the note didn't have "v" prefix for Blatann versions.
=> Cleanup of Compatibility Matrix in docs

blatann/peer.py
Fixed docstring for Peripheral method `set_conn_param_request_handler` to resolve following WARNING when building docs:
```
$ make all
Running Sphinx v7.2.6
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 94 source files that are out of date
updating environment: 0 added, 94 changed, 0 removed
reading sources... [100%] blatann.waitables.waitable
/home/mdxs/dev/gh/blatann/blatann/peer.py:docstring of blatann.peer.Peripheral.set_conn_param_request_handler:4: WARNING: Inline literal start-string without end-string.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying …
```
=> Fixed docstring for a Peripheral method

README.md
Add model/product references of supported devices to README, based on `known supported devices` in ReadTheDocs [Getting Started / Introduction](https://blatann.readthedocs.io/en/latest/getting_started.html#introduction)
=> Add model/product references of supported devices

README.md, docs/source/index.rst
Comparing the README and the ReadTheDocs introduction of Blatann showed some differences in the description (aim/goal) that this PR tries to resolve. Also expanded `bluetooth` to `Bluetooth Low Energy (BLE)` to clarify it is specifically for BLE and not Bluetooth in general (as that could be confused to also include Bluetooth "Classic"). Capitalized `Python` as official name of the language and helping readers to assess for which language this library is intended.
=> Updated description/aim of Blatann

docs/source/getting_started.rst
Applied the recent README changes to the list of supported hardware to the docs Getting Started / Introduction; and improved text of the Note about only supporting nRF52 devices with the Nordic Connectivity firmware; while also clarifying that the library will be able to communicate over BLE with non-Nordic devices (as longs as the library is used with an nRF52 device).
=> Update docs Getting Started

setup.py
Further to a suggestion shared in a comment to #161, this PR changes the short project description (as used on PyPI) in `setup.py` to "Python BLE library for using Nordic nRF52 with Connectivity firmware".
=> Update short project description

README.md
Moved the NOTE on API stability from the main introduction to the Roadmap section.
=> Moved the Note on API stability to Roadmap section

docs/source/troubleshooting.rst
Fix two small typo/grammar issues in Troubleshooting docs.
=> Fix small typo/grammar issues in Troubleshooting docs

blatann/services/nordic_uart/service.py
Current NordicUartClient limits the size of packets to MTU_SIZE_DEFAULT, this patch changes that to use the current negotiated mtu size
=> NordicUartClient to respect MTU size

tools/macos_retarget_pc_ble_driver_py.sh
This PR will add in the description that we need "Command Line Tools for Xcode" to be able to run this script which was not specified
And fix the grep command for pc-ble-driver-py
=> fix: macos retarget script

blatann/gap/smp_crypto.py
Passing the class directly throws a deprecation warning from cryptography. 
> CryptographyDeprecationWarning: Curve argument: Curve argument must be an instance of an EllipticCurve class. Did you pass a class by mistake? This will be an exception in a future version of cryptography.
See the documentation for Cryptography
https://cryptography.io/en/43.0.0/hazmat/primitives/asymmetric/ec.html
=> Pass class instance for lesc private key generation
